export interface DemoProduct {
  id: string;
  title: string;
  price: number;
  originalPrice?: number;
  images: string[];
  pickupLocation: string;
  createdAt: Date;
  isUrgent?: boolean;
  isVerified?: boolean;
  listingType: "SELL" | "RENT" | "SERVICE";
  condition: string;
  categoryId: string;
  subcategoryId?: string;
  sellerId: string;
  description: string;
  isNegotiable?: boolean;
  isExchangeAllowed?: boolean;
  seller: {
    id?: string;
    name: string;
    image?: string;
    isVerified: boolean;
    verificationLevel?: string;
    isTrustedSeller?: boolean;
    trustScore?: number;
    rating?: number;
    successfulDeals?: number;
    profile?: {
      collegeName?: string;
      course?: string;
      rating?: number;
      successfulDeals?: number;
      successRate?: number;
      avgResponseTime?: string;
    };
  };
  category: {
    name: string;
    slug: string;
  };
}

export const DEMO_TRENDING: DemoProduct[] = [
  {
    id: "demo-t1",
    title: "Apple MacBook Air M1 (2020) - 8GB / 256GB SSD (Battery Health 92%)",
    price: 42000,
    originalPrice: 79900,
    images: ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop"],
    pickupLocation: "LPU Campus, Block 34",
    createdAt: new Date(Date.now() - 3600000 * 2),
    isUrgent: true,
    isVerified: true,
    listingType: "SELL",
    condition: "LIKE_NEW",
    categoryId: "computers-laptops",
    sellerId: "seller-1",
    description: "MacBook Air M1 in pristine condition. Selling because graduating this semester. Includes original 30W USB-C charger, box, and hard shell case.",
    isNegotiable: true,
    isExchangeAllowed: false,
    seller: {
      id: "seller-1",
      name: "Rohan Verma",
      image: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop",
      isVerified: true,
      verificationLevel: "CAMPUS",
      isTrustedSeller: true,
      trustScore: 96,
      rating: 4.9,
      successfulDeals: 18,
      profile: {
        collegeName: "LPU",
        course: "B.Tech CSE",
        rating: 4.9,
        successfulDeals: 18,
        successRate: 98,
        avgResponseTime: "10",
      },
    },
    category: { name: "Computers & Laptops", slug: "computers-laptops" },
  },
  {
    id: "demo-t2",
    title: "Decathlon Riverside 120 Hybrid Cycle (21 Speed Shimano Gears)",
    price: 6500,
    originalPrice: 14999,
    images: ["https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800&auto=format&fit=crop"],
    pickupLocation: "LPU Campus, BH-4 Hostel",
    createdAt: new Date(Date.now() - 3600000 * 5),
    isUrgent: false,
    isVerified: true,
    listingType: "SELL",
    condition: "GOOD",
    categoryId: "bikes-transport",
    sellerId: "seller-2",
    description: "Smooth hybrid cycle perfect for riding across campus. Recently serviced with new brake pads and bell. Front and rear reflectors installed.",
    isNegotiable: true,
    isExchangeAllowed: true,
    seller: {
      id: "seller-2",
      name: "Aman Preet",
      image: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop",
      isVerified: true,
      verificationLevel: "CAMPUS",
      isTrustedSeller: true,
      trustScore: 92,
      rating: 4.8,
      successfulDeals: 12,
      profile: {
        collegeName: "LPU",
        course: "BBA",
        rating: 4.8,
        successfulDeals: 12,
        successRate: 95,
        avgResponseTime: "15",
      },
    },
    category: { name: "Bikes & Transport", slug: "bikes-transport" },
  },
  {
    id: "demo-t3",
    title: "LG 190L Single Door Mini Refrigerator (Ideal for Hostel Room)",
    price: 180,
    originalPrice: 16990,
    images: ["https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=800&auto=format&fit=crop"],
    pickupLocation: "LPU Campus, GH-2 Hostel",
    createdAt: new Date(Date.now() - 3600000 * 8),
    isUrgent: false,
    isVerified: true,
    listingType: "RENT",
    condition: "LIKE_NEW",
    categoryId: "furniture-hostel",
    sellerId: "seller-3",
    description: "Rent this compact fridge per day for keeping beverages, dairy, and food fresh in your hostel. Fully cleaned and sanitized.",
    isNegotiable: false,
    isExchangeAllowed: false,
    seller: {
      id: "seller-3",
      name: "Priya Sharma",
      image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop",
      isVerified: true,
      verificationLevel: "CAMPUS",
      isTrustedSeller: true,
      trustScore: 94,
      rating: 4.7,
      successfulDeals: 24,
      profile: {
        collegeName: "LPU",
        course: "B.Pharm",
        rating: 4.7,
        successfulDeals: 24,
        successRate: 99,
        avgResponseTime: "8",
      },
    },
    category: { name: "Furniture & Hostel", slug: "furniture-hostel" },
  },
  {
    id: "demo-t4",
    title: "Sony WH-1000XM4 Noise Cancelling Headphones (Black Edition)",
    price: 14500,
    originalPrice: 26990,
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop"],
    pickupLocation: "Delhi University, North Campus",
    createdAt: new Date(Date.now() - 3600000 * 12),
    isUrgent: true,
    isVerified: true,
    listingType: "SELL",
    condition: "LIKE_NEW",
    categoryId: "gaming-entertainment",
    sellerId: "seller-4",
    description: "Best noise cancellation for library study sessions! Used for 4 months with care. Battery lasts 30+ hours. Includes original carry case and aux cord.",
    isNegotiable: true,
    isExchangeAllowed: false,
    seller: {
      id: "seller-4",
      name: "Karan Gupta",
      image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop",
      isVerified: true,
      verificationLevel: "CAMPUS",
      isTrustedSeller: true,
      trustScore: 98,
      rating: 5.0,
      successfulDeals: 31,
      profile: {
        collegeName: "DU",
        course: "Economics Hons",
        rating: 5.0,
        successfulDeals: 31,
        successRate: 100,
        avgResponseTime: "5",
      },
    },
    category: { name: "Gaming & Entertainment", slug: "gaming-entertainment" },
  },
  {
    id: "demo-t5",
    title: "Ergonomic Mesh Study Chair + Foldable Wooden Desk Combo",
    price: 2400,
    originalPrice: 6000,
    images: ["https://images.unsplash.com/photo-1580481072645-022f9a6d83d0?w=800&auto=format&fit=crop"],
    pickupLocation: "Chandigarh University, Block B",
    createdAt: new Date(Date.now() - 3600000 * 18),
    isUrgent: false,
    isVerified: true,
    listingType: "SELL",
    condition: "GOOD",
    categoryId: "furniture-hostel",
    sellerId: "seller-5",
    description: "Comfortable high-back study chair with lumbar support and matching study table. Perfect setup for long exam prep nights.",
    isNegotiable: true,
    isExchangeAllowed: true,
    seller: {
      id: "seller-5",
      name: "Neha Patel",
      image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop",
      isVerified: true,
      verificationLevel: "CAMPUS",
      isTrustedSeller: false,
      trustScore: 88,
      rating: 4.6,
      successfulDeals: 8,
      profile: {
        collegeName: "CU",
        course: "M.Tech AI",
        rating: 4.6,
        successfulDeals: 8,
        successRate: 92,
        avgResponseTime: "20",
      },
    },
    category: { name: "Furniture & Hostel", slug: "furniture-hostel" },
  },
];

export const DEMO_RECENT: DemoProduct[] = [
  {
    id: "demo-r1",
    title: "Asus ROG Strix G15 Gaming Laptop (i7 11th Gen / RTX 3060 / 16GB RAM)",
    price: 58000,
    originalPrice: 112000,
    images: ["https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&auto=format&fit=crop"],
    pickupLocation: "LPU Campus, BH-1 Hostel",
    createdAt: new Date(Date.now() - 1800000),
    isUrgent: true,
    isVerified: true,
    listingType: "SELL",
    condition: "LIKE_NEW",
    categoryId: "computers-laptops",
    sellerId: "seller-6",
    description: "High performance gaming and 3D rendering laptop. Runs GTA V, Valorant, Cyberpunk smoothly. Dual fans, RGB keyboard.",
    seller: { name: "Kabir Singh", isVerified: true, verificationLevel: "CAMPUS", trustScore: 95 },
    category: { name: "Computers & Laptops", slug: "computers-laptops" },
  },
  {
    id: "demo-r2",
    title: "iPad Air 5th Gen (M1 Chip, 64GB Space Grey) + Apple Pencil 2nd Gen",
    price: 38500,
    originalPrice: 59900,
    images: ["https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop"],
    pickupLocation: "VIT Vellore, Main Gate",
    createdAt: new Date(Date.now() - 3600000 * 3),
    isUrgent: false,
    isVerified: true,
    listingType: "SELL",
    condition: "LIKE_NEW",
    categoryId: "mobiles-gadgets",
    sellerId: "seller-7",
    description: "Awesome tablet for digital note-taking and sketching. Paperlike screen protector pre-applied. Includes Apple Pencil 2.",
    seller: { name: "Siddharth Rao", isVerified: true, verificationLevel: "CAMPUS", trustScore: 97 },
    category: { name: "Mobiles & Gadgets", slug: "mobiles-gadgets" },
  },
  {
    id: "demo-r3",
    title: "Engineering Physics & Higher Mathematics Semester 1 & 2 Textbook Set",
    price: 450,
    originalPrice: 1850,
    images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop"],
    pickupLocation: "LPU Campus, Central Library",
    createdAt: new Date(Date.now() - 3600000 * 6),
    isUrgent: false,
    isVerified: true,
    listingType: "SELL",
    condition: "GOOD",
    categoryId: "books-sports-hobbies",
    sellerId: "seller-8",
    description: "Complete set of 1st year B.Tech textbooks. Marked with key highlights and exam question solved tips.",
    seller: { name: "Ananya Roy", isVerified: true, verificationLevel: "CAMPUS", trustScore: 91 },
    category: { name: "Books, Sports & Hobbies", slug: "books-sports-hobbies" },
  },
  {
    id: "demo-r4",
    title: "Single AC Private Room in 3BHK Flat (Zero Brokerage, Near Campus)",
    price: 5500,
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&auto=format&fit=crop"],
    pickupLocation: "Delhi University, Kamla Nagar",
    createdAt: new Date(Date.now() - 3600000 * 10),
    isUrgent: false,
    isVerified: true,
    listingType: "RENT",
    condition: "LIKE_NEW",
    categoryId: "properties",
    sellerId: "seller-9",
    description: "Looking for a flatmate in a fully furnished 3BHK flat. High-speed Wi-Fi, maid, RO water, and AC installed.",
    seller: { name: "Vikram Malhotra", isVerified: true, verificationLevel: "CAMPUS", trustScore: 94 },
    category: { name: "Properties & Rooms", slug: "properties" },
  },
  {
    id: "demo-r5",
    title: "Python, Java & Data Structures 1-on-1 Exam Preparation Tutoring",
    price: 299,
    images: ["https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&auto=format&fit=crop"],
    pickupLocation: "LPU Campus, CSE Block 34",
    createdAt: new Date(Date.now() - 3600000 * 14),
    isUrgent: false,
    isVerified: true,
    listingType: "SERVICE",
    condition: "LIKE_NEW",
    categoryId: "services",
    sellerId: "seller-10",
    description: "Struggling with coding assignments or lab vivas? Senior CSE student offering structured tutoring sessions on campus.",
    seller: { name: "Rahul Deshmukh", isVerified: true, verificationLevel: "CAMPUS", trustScore: 99 },
    category: { name: "Services", slug: "services" },
  },
];

export const DEMO_RENTALS: DemoProduct[] = [
  {
    id: "demo-rent-1",
    title: "Canon EOS 1500D DSLR Camera + 18-55mm Lens + 64GB Memory Card",
    price: 350,
    originalPrice: 38990,
    images: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop"],
    pickupLocation: "LPU Campus, Media Block",
    createdAt: new Date(Date.now() - 3600000 * 4),
    isUrgent: false,
    isVerified: true,
    listingType: "RENT",
    condition: "LIKE_NEW",
    categoryId: "gaming-entertainment",
    sellerId: "seller-11",
    description: "Rent for college fests, trips, or photography assignments! Includes camera bag, battery, charger, and strap.",
    seller: { name: "Kartik Nair", isVerified: true, verificationLevel: "CAMPUS", trustScore: 96 },
    category: { name: "Gaming & Entertainment", slug: "gaming-entertainment" },
  },
  {
    id: "demo-rent-2",
    title: "Sony PlayStation 5 Console + 2 DualSense Controllers + 5 Games",
    price: 499,
    originalPrice: 54990,
    images: ["https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&auto=format&fit=crop"],
    pickupLocation: "Chandigarh University, BH-3",
    createdAt: new Date(Date.now() - 3600000 * 9),
    isUrgent: true,
    isVerified: true,
    listingType: "RENT",
    condition: "LIKE_NEW",
    categoryId: "gaming-entertainment",
    sellerId: "seller-12",
    description: "Hostel weekend gaming night! Includes FIFA 24, Spider-Man 2, God of War Ragnarok, and Mortal Kombat 11.",
    seller: { name: "Harsh Vardhan", isVerified: true, verificationLevel: "CAMPUS", trustScore: 98 },
    category: { name: "Gaming & Entertainment", slug: "gaming-entertainment" },
  },
  {
    id: "demo-rent-3",
    title: "Orient Electric 32-inch HD Smart LED TV (Wi-Fi & OTT Apps)",
    price: 120,
    originalPrice: 14990,
    images: ["https://images.unsplash.com/photo-1593784991095-a205069470b6?w=800&auto=format&fit=crop"],
    pickupLocation: "LPU Campus, BH-5 Hostel",
    createdAt: new Date(Date.now() - 3600000 * 16),
    isUrgent: false,
    isVerified: true,
    listingType: "RENT",
    condition: "GOOD",
    categoryId: "furniture-hostel",
    sellerId: "seller-13",
    description: "Watch IPL matches and movies in your hostel room! Connects directly to campus Wi-Fi and mobile hotspot.",
    seller: { name: "Tarun Gill", isVerified: true, verificationLevel: "CAMPUS", trustScore: 93 },
    category: { name: "Furniture & Hostel", slug: "furniture-hostel" },
  },
  {
    id: "demo-rent-4",
    title: "Symphony Personal Air Cooler 27L (Honeycomb Cooling Pads)",
    price: 99,
    originalPrice: 6800,
    images: ["https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=800&auto=format&fit=crop"],
    pickupLocation: "VIT Vellore, Hostel Block D",
    createdAt: new Date(Date.now() - 3600000 * 22),
    isUrgent: false,
    isVerified: true,
    listingType: "RENT",
    condition: "GOOD",
    categoryId: "furniture-hostel",
    sellerId: "seller-14",
    description: "Beat the summer heat in your hostel room! Low power consumption, runs smoothly on inverter.",
    seller: { name: "Deepak Choudhary", isVerified: true, verificationLevel: "CAMPUS", trustScore: 90 },
    category: { name: "Furniture & Hostel", slug: "furniture-hostel" },
  },
  {
    id: "demo-rent-5",
    title: "Hero Sprint 26T Mountain Gear Bicycle (Front Suspension)",
    price: 49,
    originalPrice: 9500,
    images: ["https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=800&auto=format&fit=crop"],
    pickupLocation: "Delhi University, South Campus",
    createdAt: new Date(Date.now() - 3600000 * 30),
    isUrgent: false,
    isVerified: true,
    listingType: "RENT",
    condition: "GOOD",
    categoryId: "bikes-transport",
    sellerId: "seller-15",
    description: "Daily or weekly cycle rental for commuting between metro station and campus classes.",
    seller: { name: "Sameer Saxena", isVerified: true, verificationLevel: "CAMPUS", trustScore: 92 },
    category: { name: "Bikes & Transport", slug: "bikes-transport" },
  },
];

export const DEMO_VERIFIED: DemoProduct[] = [
  {
    id: "demo-v1",
    title: "Samsung Galaxy Tab S8 with S-Pen (128GB Wi-Fi / Pink Gold)",
    price: 29000,
    originalPrice: 58999,
    images: ["https://images.unsplash.com/photo-1561154464-82e9adf32764?w=800&auto=format&fit=crop"],
    pickupLocation: "LPU Campus, BH-2 Hostel",
    createdAt: new Date(Date.now() - 3600000 * 7),
    isUrgent: false,
    isVerified: true,
    listingType: "SELL",
    condition: "LIKE_NEW",
    categoryId: "mobiles-gadgets",
    sellerId: "seller-16",
    description: "Flawless tablet for PDF reading and notes. Comes with S-Pen, magnetic book cover case, and charger.",
    seller: { name: "Megha Gupta", isVerified: true, verificationLevel: "CAMPUS", trustScore: 97, isTrustedSeller: true },
    category: { name: "Mobiles & Gadgets", slug: "mobiles-gadgets" },
  },
  {
    id: "demo-v2",
    title: "Keychron K2 Mechanical Keyboard (Wireless RGB / Gateron Brown Switches)",
    price: 4800,
    originalPrice: 8490,
    images: ["https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop"],
    pickupLocation: "Delhi University, St. Stephens",
    createdAt: new Date(Date.now() - 3600000 * 11),
    isUrgent: false,
    isVerified: true,
    listingType: "SELL",
    condition: "LIKE_NEW",
    categoryId: "computers-laptops",
    sellerId: "seller-17",
    description: "Tactile mechanical keyboard for coding and typing. Connects to 3 devices simultaneously via Bluetooth.",
    seller: { name: "Devansh Mehta", isVerified: true, verificationLevel: "CAMPUS", trustScore: 99, isTrustedSeller: true },
    category: { name: "Computers & Laptops", slug: "computers-laptops" },
  },
  {
    id: "demo-v3",
    title: "Logitech MX Master 3S Wireless Ergonomic Mouse (Pale Grey)",
    price: 5200,
    originalPrice: 9995,
    images: ["https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop"],
    pickupLocation: "LPU Campus, Block 34",
    createdAt: new Date(Date.now() - 3600000 * 15),
    isUrgent: false,
    isVerified: true,
    listingType: "SELL",
    condition: "LIKE_NEW",
    categoryId: "computers-laptops",
    sellerId: "seller-18",
    description: "Quiet clicks with MagSpeed electromagnetic wheel. Works on glass surfaces. Includes Logi Bolt receiver.",
    seller: { name: "Tushar Anand", isVerified: true, verificationLevel: "CAMPUS", trustScore: 96, isTrustedSeller: true },
    category: { name: "Computers & Laptops", slug: "computers-laptops" },
  },
  {
    id: "demo-v4",
    title: "Yamaha F310 Acoustic Guitar + Padded Gig Bag & Guitar Picks",
    price: 5900,
    originalPrice: 10500,
    images: ["https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=800&auto=format&fit=crop"],
    pickupLocation: "Chandigarh University, Block C",
    createdAt: new Date(Date.now() - 3600000 * 20),
    isUrgent: false,
    isVerified: true,
    listingType: "SELL",
    condition: "GOOD",
    categoryId: "books-sports-hobbies",
    sellerId: "seller-19",
    description: "Classic acoustic guitar with warm tone. New D'Addario strings recently put on. Includes padded bag.",
    seller: { name: "Rishabh Sen", isVerified: true, verificationLevel: "CAMPUS", trustScore: 94, isTrustedSeller: true },
    category: { name: "Books, Sports & Hobbies", slug: "books-sports-hobbies" },
  },
  {
    id: "demo-v5",
    title: "Bajaj Induction Cooktop 1900W + Stainless Steel Hostel Tea & Maggi Pan",
    price: 1650,
    originalPrice: 3499,
    images: ["https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop"],
    pickupLocation: "VIT Vellore, Ladies Hostel",
    createdAt: new Date(Date.now() - 3600000 * 25),
    isUrgent: false,
    isVerified: true,
    listingType: "SELL",
    condition: "GOOD",
    categoryId: "furniture-hostel",
    sellerId: "seller-20",
    description: "Essential for late night tea, Maggi, and instant meals! Auto shut-off safety feature. Clean condition.",
    seller: { name: "Sneha Nair", isVerified: true, verificationLevel: "CAMPUS", trustScore: 98, isTrustedSeller: true },
    category: { name: "Furniture & Hostel", slug: "furniture-hostel" },
  },
];
