Add-Type -AssemblyName System.Drawing
$img = [System.Drawing.Image]::FromFile("c:\Users\harip\.gemini\antigravity\brain\3879cdb6-5881-47e5-852f-5da88ad40839\media__1778388614754.png")
# Crop more aggressively to remove bottom artifact (original height 276 -> 220)
$cropRect = New-Object System.Drawing.Rectangle(0, 0, $img.Width, 220)
$bmp = New-Object System.Drawing.Bitmap($cropRect.Width, $cropRect.Height)
$g = [System.Drawing.Graphics]::FromImage($bmp)
$g.DrawImage($img, (New-Object System.Drawing.Rectangle(0, 0, $bmp.Width, $bmp.Height)), $cropRect, [System.Drawing.GraphicsUnit]::Pixel)
$bmp.Save("c:\Users\harip\.antigravity\campus-kart\public\exown-icon.png", [System.Drawing.Imaging.ImageFormat]::Png)
$bmp.Save("c:\Users\harip\.antigravity\campus-kart\public\exown-logo.png", [System.Drawing.Imaging.ImageFormat]::Png)
$g.Dispose()
$bmp.Dispose()
$img.Dispose()
