import { MomentTemplate } from "./types";

export const MOMENT_TEMPLATES: MomentTemplate[] = [
  // ── 1. PRICE DROP (15 variations) ──
  {
    id: "price_drop_01",
    category: "PRICE_DROP",
    title: "Okay, NOW we're talking. 👀",
    message: "That {item} you saved just dropped {amount}. Your patience is terrifying.",
    cta: "See Price Drop",
    icon: "TrendingDown",
    priority: "high",
  },
  {
    id: "price_drop_02",
    category: "PRICE_DROP",
    title: "Plot twist in the marketplace.",
    message: "The seller blinked first. {item} is now {amount} cheaper than yesterday.",
    cta: "Grab The Deal",
    icon: "Tag",
    priority: "high",
  },
  {
    id: "price_drop_03",
    category: "PRICE_DROP",
    title: "Your wallet called.",
    message: "It said {item} is finally within approved budget limits after a {amount} cut.",
    cta: "Check Updated Price",
    icon: "Wallet",
    priority: "high",
  },
  {
    id: "price_drop_04",
    category: "PRICE_DROP",
    title: "Patience pays rent.",
    message: "You waited, the price fell by {amount}. We respect the discipline.",
    cta: "View Listing",
    icon: "CheckCircle2",
    priority: "normal",
  },
  {
    id: "price_drop_05",
    category: "PRICE_DROP",
    title: "We checked twice. Yep.",
    message: "That saved {item} really is cheaper now. Go look before someone else notices.",
    cta: "Inspect Deal",
    icon: "Sparkles",
    priority: "high",
  },
  {
    id: "price_drop_06",
    category: "PRICE_DROP",
    title: "Price reduction alert.",
    message: "{item} just shed {amount}. Your wishlist is heating up.",
    cta: "View Discount",
    icon: "TrendingDown",
    priority: "high",
  },
  {
    id: "price_drop_07",
    category: "PRICE_DROP",
    title: "That thing you wanted?",
    message: "It wants less money now. {amount} markdown just went live.",
    cta: "Check It Out",
    icon: "Flame",
    priority: "high",
  },
  {
    id: "price_drop_08",
    category: "PRICE_DROP",
    title: "The seller wants it gone.",
    message: "A {amount} discount on {item} just dropped. Campus deals move fast.",
    cta: "Make A Move",
    icon: "Zap",
    priority: "high",
  },
  {
    id: "price_drop_09",
    category: "PRICE_DROP",
    title: "Financial diplomacy won.",
    message: "{item} price was trimmed down by {amount}. Take a victory lap.",
    cta: "See The Cut",
    icon: "Sparkles",
    priority: "normal",
  },
  {
    id: "price_drop_10",
    category: "PRICE_DROP",
    title: "Direct notification from ExOwn.",
    message: "Your saved listing has a new lower price tag: -{amount}.",
    cta: "View Product",
    icon: "Tag",
    priority: "high",
  },
  {
    id: "price_drop_11",
    category: "PRICE_DROP",
    title: "Price update detected.",
    message: "The owner of {item} just adjusted the price down by {amount}.",
    cta: "View Offer",
    icon: "BadgePercent",
    priority: "normal",
  },
  {
    id: "price_drop_12",
    category: "PRICE_DROP",
    title: "Your radar was right.",
    message: "You bookmarked {item} at the right time. It just got discounted by {amount}.",
    cta: "Check It Out",
    icon: "Radar",
    priority: "high",
  },

  // ── 2. NEW LISTING (12 variations) ──
  {
    id: "new_listing_01",
    category: "NEW_LISTING",
    title: "Fresh drop on campus. 👀",
    message: "Someone just listed a {item} near {campus}. Fresh off the press.",
    cta: "Inspect Listing",
    icon: "Sparkles",
    priority: "normal",
  },
  {
    id: "new_listing_02",
    category: "NEW_LISTING",
    title: "New arrival. Zero airport involved.",
    message: "A fresh {item} was just listed in your campus circle.",
    cta: "See What's New",
    icon: "PackagePlus",
    priority: "normal",
  },
  {
    id: "new_listing_03",
    category: "NEW_LISTING",
    title: "Marketplace radar pinged.",
    message: "Brand new {item} just posted. You're among the first students to see it.",
    cta: "Take A Look",
    icon: "Compass",
    priority: "normal",
  },
  {
    id: "new_listing_04",
    category: "NEW_LISTING",
    title: "Someone is decluttering nearby.",
    message: "A {item} just hit the listings around {campus}. Worth a quick scroll.",
    cta: "Explore Listing",
    icon: "MapPin",
    priority: "normal",
  },
  {
    id: "new_listing_05",
    category: "NEW_LISTING",
    title: "Fresh inventory alert.",
    message: "New {item} just surfaced. First to message usually scores the best deal.",
    cta: "Check It Out",
    icon: "Clock",
    priority: "normal",
  },
  {
    id: "new_listing_06",
    category: "NEW_LISTING",
    title: "Fresh campus drop.",
    message: "A student just put up a {item} for ₹{price}. Timing is everything.",
    cta: "View New Item",
    icon: "Flame",
    priority: "normal",
  },
  {
    id: "new_listing_07",
    category: "NEW_LISTING",
    title: "Just listed 5 mins ago.",
    message: "{item} is live on ExOwn. Clean photos, campus pickup.",
    cta: "Open Listing",
    icon: "Tag",
    priority: "normal",
  },
  {
    id: "new_listing_08",
    category: "NEW_LISTING",
    title: "Your campus feed refreshed.",
    message: "New listing alert: {item}. Give it a quick look before class.",
    cta: "Browse Item",
    icon: "Zap",
    priority: "low",
  },

  // ── 3. REPEATED PRODUCT VIEW (12 variations) ──
  {
    id: "repeated_view_01",
    category: "REPEATED_VIEW",
    title: "Okay, we noticed. 👀",
    message: "Third visit to {item}. At this point, you might as well say hello to the seller.",
    cta: "Message Seller",
    icon: "Eye",
    priority: "normal",
  },
  {
    id: "repeated_view_02",
    category: "REPEATED_VIEW",
    title: "Still thinking about it?",
    message: "You've looked at {item} multiple times. Make a friendly offer and end the debate.",
    cta: "Send An Offer",
    icon: "Handshake",
    priority: "normal",
  },
  {
    id: "repeated_view_03",
    category: "REPEATED_VIEW",
    title: "You and this listing have chemistry.",
    message: "You keep opening {item}. Don't leave things unsaid — chat with the student.",
    cta: "Start Chat",
    icon: "MessageSquare",
    priority: "normal",
  },
  {
    id: "repeated_view_04",
    category: "REPEATED_VIEW",
    title: "Enough 'research'.",
    message: "You've studied {item} longer than your morning lecture notes. Hit up the seller.",
    cta: "Chat Now",
    icon: "Smile",
    priority: "normal",
  },
  {
    id: "repeated_view_05",
    category: "REPEATED_VIEW",
    title: "We won't judge.",
    message: "Repeated visits usually mean you want it. Pitch an offer before someone buys it.",
    cta: "Pitch Offer",
    icon: "Tag",
    priority: "normal",
  },
  {
    id: "repeated_view_06",
    category: "REPEATED_VIEW",
    title: "Third time's the charm.",
    message: "{item} is still available, but other campus buyers have it on their radar too.",
    cta: "Ask A Question",
    icon: "Clock",
    priority: "normal",
  },
  {
    id: "repeated_view_07",
    category: "REPEATED_VIEW",
    title: "Save yourself the screen time.",
    message: "Ask the seller your remaining questions directly in ExOwn Chat.",
    cta: "Message Now",
    icon: "MessageSquare",
    priority: "normal",
  },

  // ── 4. SAVED ITEM / WISHLIST (10 variations) ──
  {
    id: "saved_item_01",
    category: "SAVED_ITEM",
    title: "Saved to your stash. 📌",
    message: "We'll keep an eye on {item} for price cuts or status changes.",
    cta: "View Saved Items",
    icon: "Bookmark",
    priority: "low",
  },
  {
    id: "saved_item_02",
    category: "SAVED_ITEM",
    title: "Good choice.",
    message: "{item} is on your radar. We'll ping you if the seller drops the price.",
    cta: "Open Wishlist",
    icon: "Heart",
    priority: "low",
  },
  {
    id: "saved_item_03",
    category: "SAVED_ITEM",
    title: "Bookmark locked in.",
    message: "You saved {item}. Feel free to drop the seller a quick inquiry anytime.",
    cta: "See Stash",
    icon: "Sparkles",
    priority: "low",
  },
  {
    id: "saved_item_04",
    category: "SAVED_ITEM",
    title: "Eye on the prize.",
    message: "Saved items get priority price drop notifications on ExOwn.",
    cta: "Browse Wishlist",
    icon: "Eye",
    priority: "low",
  },

  // ── 5. OFFER RECEIVED (10 variations) ──
  {
    id: "offer_received_01",
    category: "OFFER_RECEIVED",
    title: "Someone just made a move. 👀",
    message: "You got an offer of ₹{amount} on your {item}. Negotiation mode: ON.",
    cta: "Review Offer",
    icon: "Handshake",
    priority: "urgent",
  },
  {
    id: "offer_received_02",
    category: "OFFER_RECEIVED",
    title: "Offer in the building.",
    message: "A buyer proposed ₹{amount} for {item}. Accept, counter, or pass.",
    cta: "Check Proposal",
    icon: "Tag",
    priority: "urgent",
  },
  {
    id: "offer_received_03",
    category: "OFFER_RECEIVED",
    title: "Your listing has a suitor.",
    message: "Someone wants your {item} and sent a fresh offer. Don't leave them waiting.",
    cta: "See Offer",
    icon: "MessageSquare",
    priority: "urgent",
  },
  {
    id: "offer_received_04",
    category: "OFFER_RECEIVED",
    title: "New campus proposal.",
    message: "A fellow student made an offer on {item}. Tap to check terms.",
    cta: "Respond Now",
    icon: "Bell",
    priority: "urgent",
  },

  // ── 6. OFFER ACCEPTED (8 variations) ──
  {
    id: "offer_accepted_01",
    category: "OFFER_ACCEPTED",
    title: "Deal locked. 🤝",
    message: "Your offer on {item} was accepted! Coordinate a safe campus meetup.",
    cta: "Coordinate Meetup",
    icon: "CheckCircle2",
    priority: "urgent",
  },
  {
    id: "offer_accepted_02",
    category: "OFFER_ACCEPTED",
    title: "And just like that... accepted.",
    message: "The seller agreed to your terms for {item}. Head to Chat to seal it.",
    cta: "Open Chat",
    icon: "Smile",
    priority: "urgent",
  },
  {
    id: "offer_accepted_03",
    category: "OFFER_ACCEPTED",
    title: "Negotiation level: 100.",
    message: "Your offer for {item} went through. One step closer to campus handoff.",
    cta: "View Deal Details",
    icon: "Sparkles",
    priority: "urgent",
  },

  // ── 7. COUNTER OFFER (8 variations) ──
  {
    id: "counter_offer_01",
    category: "COUNTER_OFFER",
    title: "Counter-offer on the table.",
    message: "The seller countered with ₹{amount} on {item}. Ball is in your court.",
    cta: "Review Counter",
    icon: "Repeat",
    priority: "urgent",
  },
  {
    id: "counter_offer_02",
    category: "COUNTER_OFFER",
    title: "Middle ground proposal.",
    message: "Seller came back with ₹{amount} for {item}. Take it or leave a reply.",
    cta: "See Counter",
    icon: "Scale",
    priority: "urgent",
  },

  // ── 8. LISTING GETTING VIEWS (10 variations) ──
  {
    id: "listing_getting_views_01",
    category: "LISTING_GETTING_VIEWS",
    title: "People are looking. 👀",
    message: "Your {item} picked up {views} views today. Expect messages soon.",
    cta: "Check Stats",
    icon: "TrendingUp",
    priority: "normal",
  },
  {
    id: "listing_getting_views_02",
    category: "LISTING_GETTING_VIEWS",
    title: "Your listing has campus eyes on it.",
    message: "{item} is trending in your category. Keep notifications handy.",
    cta: "View Listing",
    icon: "Eye",
    priority: "normal",
  },
  {
    id: "listing_getting_views_03",
    category: "LISTING_GETTING_VIEWS",
    title: "Attention detected.",
    message: "Students are checking out your {item}. Reply promptly to turn views into deals.",
    cta: "Open Inbox",
    icon: "Flame",
    priority: "normal",
  },

  // ── 9. LISTING NOT GETTING ENGAGEMENT (8 variations) ──
  {
    id: "listing_not_getting_engagement_01",
    category: "LISTING_NOT_GETTING_ENGAGEMENT",
    title: "Your listing is feeling a little quiet.",
    message: "A quick price tweak or an extra photo on {item} usually does the trick.",
    cta: "Improve Listing",
    icon: "Wrench",
    priority: "normal",
  },
  {
    id: "listing_not_getting_engagement_02",
    category: "LISTING_NOT_GETTING_ENGAGEMENT",
    title: "Give your listing a boost.",
    message: "Clear lighting and mentioning your campus block helps {item} sell faster.",
    cta: "Edit Listing",
    icon: "Sparkles",
    priority: "low",
  },
  {
    id: "listing_not_getting_engagement_03",
    category: "LISTING_NOT_GETTING_ENGAGEMENT",
    title: "Unsold? No sweat.",
    message: "Students often search for {item} on weekends. Try adjusting the price slightly.",
    cta: "Fine-tune Price",
    icon: "Tag",
    priority: "low",
  },

  // ── 10. SELL REMINDER / WEEKEND (12 variations) ──
  {
    id: "weekend_01",
    category: "WEEKEND",
    title: "It's Saturday. Your stuff is still sitting there.",
    message: "Weekend plan: clean hostel room, snap 3 photos, list on ExOwn, make bank.",
    cta: "Sell Something",
    icon: "PlusCircle",
    priority: "low",
  },
  {
    id: "weekend_02",
    category: "WEEKEND",
    title: "Hostel room inventory check.",
    message: "Got a cycle, kettle, or textbook you're not using? Turn it into weekend snack money.",
    cta: "List In 60 Seconds",
    icon: "ShoppingBag",
    priority: "low",
  },
  {
    id: "sell_reminder_01",
    category: "SELL_REMINDER",
    title: "Bro, that cycle isn't going to sell itself. 😭",
    message: "List it now, hand it off at the campus gate, and pocket the cash.",
    cta: "Post Listing",
    icon: "PackagePlus",
    priority: "normal",
  },
  {
    id: "sell_reminder_02",
    category: "SELL_REMINDER",
    title: "Your room has hidden revenue.",
    message: "Average student has 3 unused things worth ₹4,000+ taking up hostel space.",
    cta: "Start Selling",
    icon: "Coins",
    priority: "low",
  },

  // ── 11. HOUSING & ROOMMATES (15 variations) ──
  {
    id: "housing_match_01",
    category: "HOUSING_MATCH",
    title: "Hostel life getting expensive?",
    message: "Your future room might be cheaper. PGs and flats near {campus} just updated.",
    cta: "Explore Housing",
    icon: "Home",
    priority: "normal",
  },
  {
    id: "housing_match_02",
    category: "HOUSING_MATCH",
    title: "Room hunt activated. 🏠",
    message: "Verified student rooms near your campus just went live with rent details.",
    cta: "See Rooms",
    icon: "Building2",
    priority: "normal",
  },
  {
    id: "housing_match_03",
    category: "HOUSING_MATCH",
    title: "Less commute. More sleep.",
    message: "Rooms within 500m of {campus} are listed with zero broker fees.",
    cta: "Browse Flats & PGs",
    icon: "MapPin",
    priority: "normal",
  },
  {
    id: "roommate_match_01",
    category: "ROOMMATE_MATCH",
    title: "You need a roomie. They need a roomie.",
    message: "This feels suspiciously convenient. Compatible student profiles found on your campus.",
    cta: "Find Roommate",
    icon: "Users",
    priority: "normal",
  },
  {
    id: "roommate_match_02",
    category: "ROOMMATE_MATCH",
    title: "Halve your rent, double the stories.",
    message: "Check out student roommate listings filtered by sleep habits and budget.",
    cta: "Browse Roommates",
    icon: "HeartHandshake",
    priority: "normal",
  },
  {
    id: "roommate_match_03",
    category: "ROOMMATE_MATCH",
    title: "Same campus. Similar budget.",
    message: "Worth saying hello? New verified student looking for a flatmate.",
    cta: "View Matches",
    icon: "Compass",
    priority: "normal",
  },

  // ── 12. EXAM SEASON (8 variations) ──
  {
    id: "exam_season_01",
    category: "EXAM_SEASON",
    title: "Exam season detected. 🧠",
    message: "Calculators and engineering notes are suddenly the most popular items on campus.",
    cta: "Browse Study Gear",
    icon: "BookOpen",
    priority: "normal",
  },
  {
    id: "exam_season_02",
    category: "EXAM_SEASON",
    title: "Pass the notes, pass the semester.",
    message: "Don't let finished semester books gather dust. Sell them to juniors who need them.",
    cta: "Sell Textbooks",
    icon: "Library",
    priority: "low",
  },
  {
    id: "exam_season_03",
    category: "EXAM_SEASON",
    title: "Scientific calculator hunt?",
    message: "Avoid retail prices. Buy tested campus calculators from graduating seniors.",
    cta: "Find Calculators",
    icon: "Calculator",
    priority: "normal",
  },

  // ── 13. EXCHANGE OPPORTUNITY (8 variations) ──
  {
    id: "exchange_01",
    category: "EXCHANGE_OPPORTUNITY",
    title: "Trade instead of spending?",
    message: "A seller of {item} is open to exchanging for electronics or gaming gear.",
    cta: "View Exchange Options",
    icon: "Repeat",
    priority: "normal",
  },
  {
    id: "exchange_02",
    category: "EXCHANGE_OPPORTUNITY",
    title: "Circular campus economy at work.",
    message: "Swap what you don't need for what you do. Check listings with Exchange ON.",
    cta: "Explore Barter",
    icon: "RefreshCw",
    priority: "low",
  },

  // ── 14. WELCOME & RE-ENGAGEMENT (10 variations) ──
  {
    id: "welcome_01",
    category: "WELCOME",
    title: "Welcome to ExOwn. 🎉",
    message: "Your campus marketplace starts here. Buy smarter, sell easier, avoid campus scams.",
    cta: "Explore Marketplace",
    icon: "Sparkles",
    priority: "low",
  },
  {
    id: "welcome_02",
    category: "WELCOME",
    title: "Glad you're here!",
    message: "All listings come from university students. Check out trending deals on your campus.",
    cta: "See What's Hot",
    icon: "Compass",
    priority: "low",
  },
  {
    id: "re_engagement_01",
    category: "RE_ENGAGEMENT",
    title: "We haven't seen you in a while. 👀",
    message: "The campus marketplace has been busy. New gadgets and textbooks just got listed.",
    cta: "See What's New",
    icon: "Bell",
    priority: "low",
  },
  {
    id: "re_engagement_02",
    category: "RE_ENGAGEMENT",
    title: "Things moved while you were away.",
    message: "Check your saved searches for fresh campus drops.",
    cta: "Check Feed",
    icon: "Activity",
    priority: "low",
  },

  // ── 15. SAFETY & SECURITY (8 variations) ──
  {
    id: "safety_01",
    category: "SAFETY_SECURITY",
    title: "Campus safety tip from ExOwn 🛡️",
    message: "Always meet in public campus spots (Library, Cafeteria, Main Gate) for item handoffs.",
    cta: "Read Safety Guide",
    ctaHref: "/safety",
    icon: "ShieldCheck",
    priority: "normal",
  },
  {
    id: "safety_02",
    category: "SAFETY_SECURITY",
    title: "Never pay upfront to strangers.",
    message: "Inspect the item in person before transferring money. Safe campus deals only.",
    cta: "Safety Rules",
    ctaHref: "/safety",
    icon: "ShieldAlert",
    priority: "normal",
  },

  // ── 16. HELPFUL ADVICE (8 variations) ──
  {
    id: "helpful_advice_01",
    category: "HELPFUL_ADVICE",
    title: "Pro tip for faster sales 💡",
    message: "Listings with 3+ well-lit photos and battery health details sell 2.5x quicker.",
    cta: "Got It",
    icon: "Lightbulb",
    priority: "low",
  },
  {
    id: "helpful_advice_02",
    category: "HELPFUL_ADVICE",
    title: "Looking for rental gear?",
    message: "You can rent cycles, lab coats, and monitors for short semesters without buying.",
    cta: "Browse Rentals",
    ctaHref: "/search?listingType=RENT",
    icon: "KeyRound",
    priority: "low",
  },
];
